### ISSUE TITLE
Configure Logging for CLI?

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.core#17]
@href Is there a reason that the logging is not configured when running cli programs? Or can we enable this? Probably at https://github.com/OneGov/onegov.core/blob/master/onegov/core/cli/core.py#L527, maybe something like:

```
server = Server(
   Config({
        'applications': applications,
        'logging': Config.from_yaml_file(config).logging
    }),
    configure_morepath=False
)
```

**Comment by href** [comment]
I think we can enable this. Be careful though, not all config files have a logging part setup so you shouldn't require it. I also think you don't need to parse the yaml file again, as we are doing this already when we setup the context:

https://github.com/OneGov/onegov.core/blob/master/onegov/core/cli/core.py#L289

**Comment by msom** [comment]
👍🏻 

([`logging` is set per default to an empty dict](https://github.com/OneGov/onegov.server/blob/master/onegov/server/config.py#L21))
