### ISSUE TITLE
TranslationHybrid Not Working with Multiple Applications

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.core#21]
The translation hybrid [reads from the wrong session mananger](https://github.com/OneGov/onegov.core/blob/6233ed566727ec4f44a879c54f46efb0181a9664/onegov/core/orm/__init__.py#L65) when using multiple application (i.e. the [last created session manager of the applications](https://github.com/OneGov/onegov.core/blob/bae778f1886a94ede4e2e590b85e6193f615685f/onegov/core/orm/session_manager.py#L331)).

**Comment by href** [comment]
I've fixed this in the [latest commit](https://github.com/OneGov/onegov.core/commit/2f4f65c4d5b87e1650cbbd04a5147c4041577244). The gist of it is that we now have a global reference to the currently active session manager, which can be manipulated through `session_manager.activate()` (though there should not be a reason to do this manually outside of tests).

All tests seem to still pass, though onegov.election-day's `test_archived_result_collection` fails sometimes. Could you verify if this is a separate issue?

**Comment by msom** [comment]
The CLI part of onegov.core seems to overwrite the global session manager when creating an unbound session manager:

https://github.com/OneGov/onegov.core/blob/a0c6da531519006a5bdbe86299c23d5e2f753883/onegov/core/cli/core.py#L327

It probably also overwrites locale settings when using the request/application context:

https://github.com/OneGov/onegov.core/blob/a0c6da531519006a5bdbe86299c23d5e2f753883/onegov/core/cli/core.py#L601

This seems to be a problem only when running CLI tests, running those test [in a separate process](https://github.com/OneGov/onegov.election_day/commit/882cf24ce966512f9289d1af9a3a0b0a46c8365a) seems to avoid these problems.

**Comment by href** [comment]
The session manager is no longer used for the cli core, can you check if this solves the problem?

**Comment by msom** [comment]
I think there still might be a problem when `cli.command_group` creates a server and makes requests to it (because it's in the same thread).

**Comment by href** [comment]
Do you have a test-case that I can run?

**Comment by msom** [comment]
It looks like it was caused by https://github.com/OneGov/onegov.core/pull/22.
