### ISSUE TITLE
Can we add the group to the identity policy?

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.core#25]
Remembering the ID of the group (the UUID as string) would allow to easily define permission rules and save some overhead in projects where some permissions to specific models are based on groups rather the roles (gazette, wtfs).

It's not a big change (https://github.com/OneGov/onegov.core/compare/groupid) and the changes needed elsewhere are minimal (https://github.com/OneGov/onegov.user/compare/groupid).

The behaviour when updating existing apps is straight forward: All users are logged-out due to the missing new key in the existing browser sessions (we purge the cache after an update anyway).

Is there a reason we store the username (=email) as userid and not the UUID? In onegov.activity, the username is stored as owner and used in the permission rules. In onegov.notice, I use the UUID of the user which allows to easily change to email of the user without any side effects (but requires to query the user when needed). I think it would be good if we use the same approach everywhere (e.g. using UUID for userid/groupid, or introduce a username-like column to the user group and use that).

**Comment by href** [comment]
Go ahead 👍
