### ISSUE TITLE
Improve Postgres Extension Mechanism

### ISSUE THREAD

**Issue by href** [OneGov/onegov.core#5]
The `CREATE EXTENSION` call in the schema setup has a few issues:
- It can only be executed as superuser.

A sysadmin shouldn't use a superuser connection for onegov.town, so he has to create the extension in a separate step. If it exists, the create extension call will work even if the user doesn't have the right to actually create the extension. So we should document the required extensions somewhere.
- It makes no sense to create the extension for each schema - extensions are global.

Change the code to only be called once for each database connection.
- It is a package dependent thing and shouldn't technically be done in the core.

It would be nice if the packages could register the extensions they need with the core. So the core doesn't have to know about extensions. Have a look at how onegov.core.upgrades handles entry_points. We could use the same system to advertise the extensions to the core. This way we don't pay the cost of the extension if we don't need it.

The last point can be done in a separate step. For now it doesn't bug me too much, but it is not something we can sustain for too long.

**Comment by href** [comment]
Also, since the create extension call is only run when the schema already exists, it won't ever be asserted for existing schemas.

The call should happen once (and only once) per connection. It would be good to have a test for that.

**Comment by msom** [comment]
Extensions unfortunately not so global as it seems... We could create a schema for each extension and add this schema to the `search_path`, see http://stackoverflow.com/questions/12986368/installing-postgresql-extension-to-all-schemas.

**Comment by href** [comment]
Yeah, the docs are interesting:

> Remember that the extension itself is not considered to be within any schema: extensions have unqualified names that must be unique database-wide. But objects belonging to the extension can be within schemas.

So they are bound no schema, except that they are.

**Comment by href** [comment]
The extensions are now bound to the 'extensions' schema which is added to the search path:
https://github.com/OneGov/onegov.core/commit/b9c60d66fc6ec906d422bbafcb0439264edee7ed

There's a test that verifies this works.

**Comment by href** [comment]
Note that this is not yet part of deplyoment. Once onegov.event is integrated into onegov.town we need to add this to the deployment and test it thoroughly before upgrading the existing instances.
